import type { ThemeDefinition } from 'vuetify';

const lightTheme: ThemeDefinition = {
    dark: false,
    colors: {
        background: '#F6F4EB',
        surface: '#91C8E4',
        'surface-bright': '#91C8E4',
        'surface-variant': '#424242',
        'on-surface-variant': '#91C8E4',
        primary: '#4682A9',
        'primary-darken-1': '#3700B3',
        secondary: '#03DAC6',
        'secondary-darken-1': '#018786',
        error: '#B00020',
        info: '#2196F3',
        success: '#4CAF50',
        warning: '#FB8C00',
        'on-background': '#000',
        'on-surface': '#000',
        'on-surface-bright': '#000',
        'on-primary': '#fff',
        'on-primary-darken-1': '#fff',
        'on-secondary': '#000',
        'on-secondary-darken-1': '#fff',
        'on-error': '#fff',
        'on-info': '#fff',
        'on-success': '#fff',
        'on-warning': '#fff',
    },
    variables: {
        'border-color': '#000000',
        'border-opacity': 0.12,
        'high-emphasis-opacity': 0.87,
        'medium-emphasis-opacity': 0.6,
        'disabled-opacity': 0.38,
        'idle-opacity': 0.04,
        'hover-opacity': 0.04,
        'focus-opacity': 0.12,
        'selected-opacity': 0.08,
        'activated-opacity': 0.12,
        'pressed-opacity': 0.12,
        'dragged-opacity': 0.08,
        'theme-kbd': '#212529',
        'theme-on-kbd': '#FFFFFF',
        'theme-code': '#F5F5F5',
        'theme-on-code': '#000000',
    },
};

export { lightTheme };
